### ISSUE TITLE
Special characters on title when publishing

### ISSUE THREAD

**Issue by viktormorales** [OpenLiveWriter/OpenLiveWriter#114]
I own a self hosted wordpress blog and started testing OLW a few days ago. Loving it so far! But I noticed when publish a post, the title show the special characters as codes, for example: "Let&quot;s do it world."

I don't know C#, so... just sharing the "issue".

**Comment by pekiZG** [comment]
@viktormorales tnx for reporting this.

Would you be so kind and describe steps to reproduce this issue?

**Comment by viktormorales** [comment]
Hi @pekiZG! Sure I can.

I write the title on OLW and then publish:
![olw-1](https://cloud.githubusercontent.com/assets/1565556/11764251/7925432a-a107-11e5-983b-acdf24c28874.jpg)

When I go to edit it from the wordpress admin panel:
![olw-2](https://cloud.githubusercontent.com/assets/1565556/11764261/a3ba8d16-a107-11e5-950c-7b0fcb842afc.jpg)

This is not a problem when reading the post, because the HTML codes are correctly coded:
![olw-3](https://cloud.githubusercontent.com/assets/1565556/11764292/e1907a50-a108-11e5-860e-f0a14693b3de.jpg)

But it's not good in permalinks, because "acción" is "accin", that permalinked word miss its meaning.

Is this information useful?

**Comment by LouisStAmour** [comment]
That's very useful. :) So special characters are encoded as HTML entities... Haven't contributed yet to this project but my first assumption is that we're working with XML or an API that can work both with UTF8 and what we have here, HTML entities. If there's an existing option to use Unicode or UTF8 in preferences somewhere, I would try that.

Unicode is preferred these days but it used to be that with AJAX and form data, IE would misbehave with special characters unless you happened to use them in the URL of the request, which is why Rails would insert a snowman in a hidden field. There were other issues in other browsers, but it's been at least a decade since browsers had trouble displaying UTF8 with the exception of some web font issues.

Which brings us to the second part of the problem, Unicode has to be declared, it's not yet entirely the default, particularly because UTF8 doesn't always "declare itself" and until recently, could not entirely represent some languages. (New characters are still being added, in fact...)

So you have to make sure your server will work with UTF-8 and that your webpage is served following web standards to declare its charset (character set) as UTF-8. This isn't always compatible, particularly if you in fact don't want to use UTF-8 with Open Live Writer for esoteric reasons.

I agree, the code currently uses deprecated functions to encode HtmlEntities -- this behaviour needs to be looked at for forward-compatibility with 2015's expectations and modern systems that are much more Unicode compatible. I'd hate to introduce a checkbox--but this does feel like a bit of a breaking change. If there's a new major release planned by anybody, I'd break this to deliver Unicode-first in a heartbeat. There's about 20-40 places in the code where HTML entity encoding and decoding is performed. Note, we cannot remove it all -- we need to accept input with entities still. And the question remains, if a character is imported with an entity, should it be saved as an entity for compatibility or as Unicode? My preference is rewriting, but maybe the character has good reason -- particularly if MySQL or the platform doesn't support UTF-8. These days, I feel UTF8 collation is a given though.

Good bug report, thanks. I should start contributing to this project! :)

**Comment by viktormorales** [comment]
I've been checking the options, but nothing in there. Have a great contribution! I will keep on posting with OLW and spreading the word of it's reencarnation heheh. It's a great resource when hitting the road and there's no Internet. Thumbs up!

**Comment by ScottIsAFool** [comment]
You can try changing the encoding for that blog in the Writer options:
![image](https://cloud.githubusercontent.com/assets/1658896/11767514/2c181822-a1a8-11e5-8d2d-b51d87b9c7dc.png)

**Comment by willduff** [comment]
@LouisStAmour Thanks for the great write up. For the long term, it would be nice to make those breaking changes that you mention and move to more modern standards. 

My recommendation would be to make the change but put it behind a checkbox, like you mention. That way the default implementation doesn't change, but we can ask users to go check the checkbox, try it out and let us know if the output still looks good. @RobDolin has an email list of volunteers interested to help test out the product and we could contact them. Once we feel like we've gotten enough coverage of the feature, we can flip it on by default and eventually remove the setting and the old code when its stable.

We may still need to encode some characters in the title as HTML if the blog configuration 'Requires HTML Titles' is `true` (this corresponds to `IBlogClient.RequiresHtmlTitles`). For example angle brackets `<` would likely need to be encoded on some blog clients, otherwise they'll be interpreted as HTML tags. I'd want to do some testing on this ourselves with at least Wordpress before checking in the code and asking others to try it out.

**Comment by LouisStAmour** [comment]
HTML in post titles is a tricky use case. If we consider blogs to be purely sites that export RSS, then HTML is usually only supported in post bodies, by either escaping it using hexadecimal entities (because XML doesn't usually have HTML entities) or using a CDATA section (which I personally prefer, because it has less ambiguities around double-escaping, but which XML purists could argue against because it doesn't validate). See also: http://www.rssboard.org/rss-profile That said, this is a case where RSS disagrees with Atom, which appears to allow (expect?) HTML in titles. There's again a debate on double-encoding: https://core.trac.wordpress.org/ticket/9992 Here it ends with accepting the HTML encoding (even if it appears to be double-encoding) because ultimately, it's Atom and meant to be a literal string of HTML encoded using CDATA. 

So to sum up, yes, in cases where input should not be HTML, we obviously need to escape that. I wouldn't say this applies only to the title -- I'd suggest this applies evenly across the board. If the user types in `<` then makes it bold, the result should be `<![CDATA[<b>&gt;</b>]]>` in both description and title. If the user types `<b>&gt;</b>` then that becomes `<![CDATA[&gt;b&lt;&amp;gt;&gt;/b&lt;]]>` unless it's typed in some kind of "raw text" or HTML-expected input field. Or at least, that's my assumption.

It likely depends on the posting mechanism. If we can submit via a known standard like Atom or RSS, it's easier. I'm quickly looking up Wordpress posting standards now to see which we can follow:

They supported Atom without a plugin until 3.5, where you then had to enable it manually: https://codex.wordpress.org/AtomPub It was removed due to disuse: https://core.trac.wordpress.org/ticket/21866

The XML-RPC MetaWeblog API is based on RSS, thus it's supposed to exclude HTML from titles, etc., and only expect it in description. The implementation docs are vague: https://codex.wordpress.org/XML-RPC_MetaWeblog_API

This post with a VBA script for Word to publish using XML-RPC references CDATA as a way to have wordpress stuff it unmodified into the database (not sure if this applies to modern versions, but given that Wordpress parses WXR using Regex, it's still a good possibility), which means it should be valid HTML and not screw up the page when loaded by Wordpress: http://www.juust.org/index.php/metaweblog-newpost-posting-to-wordpress-from-word/2009/10/

Hmm. Looking at existing documentation at https://msdn.microsoft.com/en-us/library/bb463260.aspx?f=255&MSPPError=-2147217396 I can agree with the requirement of a checkbox for HTML in titles. I wonder ... how far should we take customizing Live Writer to better support individual blogging platforms, and new ones that have appeared since? It'd be great to support custom fields, but then where do you stop? Page types from WordPress? Custom types? We'd want a generic way to handle these, perhaps an extension to existing options support. But that's a different bug/issue entirely.

http://docs.orchardproject.net/Documentation/xml-rpc has links to common XML-RPC-based posting APIs. I now understand why few modern clients support XML-RPC with such limited documentation available, it's a shame AtomPub wasn't promoted earlier.

Again, this is probably a different post entirely, but if we're looking at handling encoding, it could be good to compare ourselves (and our XML-RPC support) with the expectations of other APIs to come up with a more general solution.

* Medium: https://github.com/Medium/medium-api-docs JSON-based, which means "All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F)." Title unspecified, so probably plain text. Can receive HTML or Markdown. Post content must be valid HTML, accepts a subset of HTML.
* Google+ posts in a limited way (for domains) and doesn't support a title. It too uses JSON in its protocol: https://developers.google.com/+/domains/posts/attaching-urls
* SharePoint's JSON/OAuth-based REST API is unclear on how it supports blogging, instead there's still a (legacy?) XML-RPC endpoint in that type of site. Their new REST API is OAuth-enabled and JSON-based, thus suggesting we'll want to support OAuth at some future date, if not already. Medium's API was also OAuth2-enabled.
* MovableType has a new REST API in v6 as documented at https://github.com/movabletype/Documentation/wiki/Movable-Type-Data-API however they continue to support what appear to be 3 forms of Atom API and 4 forms of XML-RPC: https://movabletype.org/documentation/developer/api/
* The Blogger API 1.x has been updated to 2.x using OAuth2 but still uses XML as before, and I see support for Google's OAuth2 was added to Live Writer. It could perhaps be made more generic, as a separate TODO. https://developers.google.com/blogger/docs/2.0/developers_guide_protocol?csw=1
* That said, there's a Blogger API 3.x that now uses JSON: https://developers.google.com/blogger/docs/3.0/using#AddingAPost and I see you're now adding support for it, @willduff so ... maybe this is more useful for you personally or maybe I'm mentioning things you already know :+1: #5 
* Tumblr #32 has a custom API, since they (like wordpress and Google+) support different post types. There, the title is optional, and HTML entities must be escaped though it's actually JSON as an API. (No HTML supported?)
* Wordpress.com (and third-party blogs via Jetpack?) now supports a REST API that's OAuth2-backed: https://jetpack.me/support/json-api/ There's work underway for other plugins for Wordpress, but the OAuth2 plugin is separate from the JSON API plugin in other implementaions.
* SquareSpace #42 Used to support XML-RPC back in v5 but switched in v6 and beyond to prefer their own apps instead. Their developer pages are for building websites, not posting via an API. Documented at: https://support.squarespace.com/hc/en-us/articles/206545167-Can-I-use-an-XML-RPC-client-with-Squarespace-
* Svbtle, Ghost, Posthaven, and many others either don't have an API or are still working on it.
* LinkedIn: Again, OAuth2, JSON: https://developer.linkedin.com/docs/company-pages#company_share
* Facebook & Twitter ... well, of course they've JSON-based APIs. But it then brings up the question of "posting to multiple places automatically" or cross-posting to social media specifically.
