### ISSUE TITLE
Cannot connect to my blog using Metaweblog API

### ISSUE THREAD

**Issue by tleclaire** [OpenLiveWriter/OpenLiveWriter#128]
When I try to connect to my blog using metaweblog API provider I receive an error message, that the URI of the remote posting web adress is invalid allthoughj I tripple checked and it is and works in old live writer. The adress looks like http://kt2016.mysite.de/metaweblog.axd and it seems that it cannot be parsed for whatever reason.

**Comment by RobDolin** [comment]
@tleclaire  Thanks very much for trying Open Live Writer and for reporting this issue.  Can you check the web address of your blog?  I tried browsing to: http://kt2016.mysite.de/ and it looks like a placeholder page rather than a blog.  Also do you know what blogging software platform is being used for your blog?  Thanks again.

**Comment by RobDolinMS** [comment]
Per conversation with @tleclaire, I think #135 would resolve this issue.
