### ISSUE TITLE
Add spell check feature back in OLW

### ISSUE THREAD

**Issue by lon3wolf** [OpenLiveWriter/OpenLiveWriter#130]
We can use the built-in API provided by windows [Spell check API!](https://msdn.microsoft.com/en-us/library/windows/desktop/hh869748(v=vs.85).aspx)

**Comment by robertjm** [comment]
This is a big issue IMHO. Don't know about others. But, I relied on the Live Writer spell check quite a bit even though I consider myself a decent speller.

**Comment by aabelro** [comment]
+1
Currently, I copy the text to LW to do the spell checking, then, if I made a correction, I copy it back to OLW. We need to spell check everything before pushing it out there.

**Comment by lon3wolf** [comment]
A pull request  #213 already exists to fix this.
Once a decision is made to merge and release it, issue should be fixed

**Comment by willduff** [comment]
Huge thanks to @bbowyersmyth for fixing this issue! Spell checking will be enabled in the next official Open Live Writer release.

**Comment by robertjm** [comment]
Thanks @bbowyersmyth !! How often doe official releases get put out?

**Comment by lextm** [comment]
Should make it very clear that spell check feature is only supported on Windows 8 and above, as "the Spell Checking API is available beginning with the Windows 8 or Windows Server 2012".

**Comment by ScottIsAFool** [comment]
@lextm you mean like we did in the blog post detailing the release? http://openlivewriter.org/news/release/2016/02/13/version-0-dot-6-now-available.html

**Comment by lextm** [comment]
@ScottIsAFool no Scott. I don't mean that. The release notes look great though.

Many threads/issues on GitHub on the other hand, only contains partial information, which is my concern. For example, if anyone comes to this thread, he/she might not get the key information like which OS is supported by spell check feature, and then he/she will be surprised to see this feature is disabled (on Windows Vista or Windows 7 as #209 revealed).

Even googling "spell check Open live writer" won't lead us to the 0.6.0.0 release notes easily. 

I believe we need a better way to tell the users. Maybe a pull request to enhance the spell check feature, so that it explicitly tells the users on Windows Vista/7 that they should upgrade.
