### ISSUE TITLE
Stop uploading 3 copies of images to blog host

### ISSUE THREAD

**Issue by Laronski** [OpenLiveWriter/OpenLiveWriter#140]
In previous Windows Live Writer versions, Windows Live Writer uploaded 3 versions of all images to the blog svc. I would llike to see Open Live Writer handle this more intelligently; only uploading the images needed. Or maybe just thumbnails and orginals.

**Comment by timheuer** [comment]
@Laronski I am pretty sure this is 'by design' and controlled by two things: 1) the choice selected in this option (by default on my wordpress site it says link to original picture):

and 2) the blog engine and/or server side.
<img width="324" alt="piclink" src="https://cloud.githubusercontent.com/assets/4821/11796874/d984fa4a-a273-11e5-9612-e978ba7f7be1.PNG">

What blog engine do you use?  I've only seen it upload 2 copies (thumb + original) unless you are doing something different, I can't imagine it doing more than that...what is your repro?

**Comment by Laronski** [comment]
I primarily use WordPress, and it seems to work fine in WordPress. But In Blogger, it never fails; there was always 3 copies of the same image. I just thought it was a waste of storage space.

"what is your repro?" Reproducing the error/issue?
I just upload to Blogger form Windows Live Writer. Images are stored on the Google Google Picasa [it think]. I could be wrong, I haven't logged into the Windows Live Writer images folder in years. I'll remove this issue if I can't verify.
