### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by dend** [OpenLiveWriter/OpenLiveWriter#50]
Adding this to the backlog of items that I would want to work on. Comment here if you are interested to be a part of a Mac port for this project.

**Comment by SachiraChin** [comment]
I'm interested in contributing this version. Been working with Core CLR recently and have experience in Obj-C and C.

**Comment by milizhang** [comment]
The current code relies heavily on WinForms. 
Unless you want to use the Mono's implementation of WinForms (which seems to be X11 only), finding a substitution and decoupling the UI from WinForms would be the first thing toward cross-platform.

**Comment by SachiraChin** [comment]
I think Mono's [WinForms supports OS X](http://www.mono-project.com/docs/faq/winforms/#does-winforms-run-on-osx). I noticed that repo contains come C++ library for ribbon UI, we have to look into that as well.

I will try Mono WinForms in my fork to see how it'll go and how much work it may need.

**Comment by martinwoodward** [comment]
@SachiraChin way to go - let us know how you get on.

**Comment by glennblock** [comment]
+1 for Mac. I bought Mars to use for blogging. It doesn't hold a flame to LW

**Comment by juvander** [comment]
Yes, would definitely contribute to this!

**Comment by SachiraChin** [comment]
@martinwoodward I was able get managed projects build without errors. But OpenLiveWriter.Ribbon project does not work or can be built on Xamarin Studio. I think I won't be able to build it with Mono because of the dependency of uicc.exe. Any suggestion to solve this would help me a lot. Meanwhile, I will look for alternatives.

**Comment by SachiraChin** [comment]
@juvander I've pushed updated code to my repo. You are welcome to try. Thanks.

**Comment by juvander** [comment]
Took a quick peak, lots of stuff that need rework :(

**Comment by SachiraChin** [comment]
I will log changes I do here so you guys can track.

- Able to get application build by removing OpenLiveWriter.Ribbon. 
- Had to remove ```Kernel32.SetDllDirectory("");``` and ```WindowsIdentity currentUser = WindowsIdentity.GetCurrent();``` from startup because it does not supported.
- There's dependency for urlmon.dll which found on Windows. Trying to native Windows lib in Mac. Following guidelines on [http://www.mono-project.com/docs/advanced/pinvoke/#mac-os-x-framework-and-dylib-search-path](http://www.mono-project.com/docs/advanced/pinvoke/#mac-os-x-framework-and-dylib-search-path). Currently it does not load copied dll. May be it can't pinvoke Windows dlls...

**Comment by xiexin36** [comment]
@SachiraChin mono can only call dylib on os x, and Mono does not support managed C++.

**Comment by xiexin36** [comment]
Maybe we can change the UI to gtksharp, like monoDevelop, in our project, we changed wpf to gtksharp

**Comment by SachiraChin** [comment]
That's what I thought as well, but application functions heavily depends on Windows native libraries, not the UI. Even if we port UI to gtksharp, we still need find/rewrite alternatives to native assembly calls. I will update here the native functions which application depends on, we can discuss whether these can be rewritten from C# or not.

**Comment by xiexin36** [comment]
@SachiraChin  Yes, some windows native libraries, maybe we can use MonoMac or Xamarin.Mac to instand of, these dlls wrapper the OS X CoreFunction in C#.

**Comment by SachiraChin** [comment]
@xiexin36 Yes I think it’s a good idea, working on getting available native library calls. If you want to see it, all of those are inside one project [OpenLiveWriter.Interop](https://github.com/OpenLiveWriter/OpenLiveWriter/tree/master/src/managed/OpenLiveWriter.Interop).

**Comment by imhazige** [comment]
+1
I really need it, looking for this feature for years already, now it is the good time to have it as it opensource now!

**Comment by DukeCheng** [comment]
Does any updates on this issue?
