### ISSUE TITLE
Install: Add OLW package to Chocolatey

### ISSUE THREAD

**Issue by DavidBurela** [OpenLiveWriter/OpenLiveWriter#57]
Adding Open Live Writer to Chocolatey opens up installation scenarios https://Chocolatey.org/ 

My assumption is that we would just initially install via the Setup.exe. And from there the Squirrel auto updater keeps the version up to date. There shouldn't be any reason to increase the chocolatey package version to manually upgrade.

**Comment by DavidBurela** [comment]
I've spent days reading the Chocolatey documentation to try and figure out how to create a package for another project, but unfortunately I STILL haven't figured it out. So I won't be able to resolve this one myself sorry.

**Comment by gep13** [comment]
@DavidBurela I was actually just looking at what would be required here.  I am part of the Chocolatey Development Team, and I would love to see this package added to Chocolatey :+1: 

What sort of things are you running into?  Feel free to ask any questions that you might have, happy to help out.

I have just ran the Setup.exe that is generated as part of the build, and I noticed that there are a number of user interaction screens that you have to go through.  Can all of those screens been made silent, by passing in the parameters to the setup.exe?  That would be the ideal situation, as we prefer Chocolatey Packages to install silently, but also to be configurable?

I haven't dug into the code yet, but I simply ran the `build.cmd` and I got a generated nupkg in the releases folder.  Was this nupkg generated as part of the compilation of the solution?  If so, what is the BuildNuget.cmd for?

**Comment by ScottIsAFool** [comment]
BuildNuget.cmd is for the SDK nuget package.

**Comment by martinwoodward** [comment]
The Open Live Writer install uses the excellent [Squirell](https://github.com/Squirrel/Squirrel.Windows/) to create our evergreen installer. Try the following in the Chocolatey script to silently install and show the initial setup dialogs on first run:

```
Setup.exe --silent
```

**Comment by gep13** [comment]
@martinwoodward said...
Try the following in the Chocolatey script to silently install

@martinwoodward that sounds perfect! I can give that a try, thanks!

**Comment by martinwoodward** [comment]
Make sure you follow along with #27 in case the name of Setup.exe changes...

**Comment by gep13** [comment]
@martinwoodward Yip, I was thinking the same thing.  Was going to add a note to this issue, once I create the PR for creating the Choco Package.

**Comment by gep13** [comment]
It should simply be a change to the new nuspec file if the name of the exe changes.

**Comment by gep13** [comment]
@martinwoodward actually, I lied, it will be two places :smile:

**Comment by DavidBurela** [comment]
@gep13 FYI you'll need to update the filename to OpenLiveWriterSetup.exe as per #27

**Comment by gep13** [comment]
@DavidBurela already taken care of :smile: 

https://github.com/OpenLiveWriter/OpenLiveWriter/pull/75/files#diff-ebdf39768a79ce99017fdf3146bf4eaeR22
https://github.com/OpenLiveWriter/OpenLiveWriter/pull/75/files#diff-1b7d29e82cbd74b5e28fed39e47a8cc1R5

**Comment by DavidBurela** [comment]
Thanks to @gep13 the package is now up on chocolatey https://chocolatey.org/packages/openlivewriter

As it isn't approved yet, I was able to install it manually by specifying the version 
`choco install openlivewriter -y -version 0.5.0.0`
It installed fine and appeared in my start menu.

I think we should leave the issue open until the package has been approved by moderation and is able to be installed.

**Comment by gep13** [comment]
@DavidBurela the thanks actually needs to go to @darwinjs, as it was him that really did the hard work :-)

I would suggest that this issue should remain open until the associated PR is merged in.  That way, we know that going forward, the application will make it into Chocolatey.org with each release.

**Comment by DavidBurela** [comment]
Hmm, do we WANT a new chocolatey release each time there is a new version?
Doing a chocolatey upgrade wouldn't do much will it, as the app is auto updating? What does happen if you run a chocolatey upgrade with the squirrel installer?

**Comment by gep13** [comment]
@DavidBurela I would suggest that the most up to date version of the application should be available on Chocolatey.  Agreed, not expecting people to use `choco upgrade` to update it, as the Squirrel updater will take care of that.  But anyone new to the application, who wants to use the application, shouldn't be penalised by having to first download an older version, and then have to immediately update it.

**Comment by DarwinJS** [comment]
It's probably not so important with an end user application like this - but
being able to access old versions of utility software through automation is
an important value of a repository like Chocolatey.org.  All too often some
development stacks are dependent on old versions due to the effort and cost
to refactor and test to get onto newer ones.

Again - probably not a concern here.

It would be nice if chocolatey had specific instrumentation for indicating
when you want the latest underlying package.  Like version
9999.9999.9999.9999 meaning "grab the installer that is the latest from the
vendor site".  Then just like many website's download sections there could
be a fixed "latest" version and versioned releases for all previous
releases.

This is a place where Chocolatey could add value to Nuget - since the
concept does not make sense in native Nuget since it does not conceive
directly of installation binaries being dynamically fetched.

D.

**Comment by martinwoodward** [comment]
The Chocolately package includes the setup exe which just contains the evergreen installer logic.  Setup.exe goes to the CDN and downloads a file called RELEASE which indicates the location of the actual binary bits which get installed on your machine.  Therefore the Chocolatey package will always install the latest version of the application.

That said - even it if installed an old version then when you opened Open Live Writer it checks for updates on start-up and downloads the latest version and silently upgrades on first start up.

So, probably doesn't make much sense to have a version in the Chocolately package as it's whatever is the stable version at the time of install.

**Comment by DarwinJS** [comment]
Yep - I think what you're saying makes sense!
D.

**Comment by gep13** [comment]
>@martinwoodward said....
So, probably doesn't make much sense to have a version in the Chocolately package as it's whatever is the stable version at the time of install.

Ah, that is interesting.  That must be a side effect of the Squirrel installer, which I wasn't aware of.  Is there any way to bundle the RELEASE file into the Chocolatey package as well, rather than have it hit the CDN?  Does this even make sense?  Ideally, the Chocolatey Package version, which is immutable, will actually install the listed version number of the application.  

This is not a requirement.  For example, the Atom Chocolatey Package always installs the latest version of Atom, regardless of the listed version number on Chocolatey.org.  This is just a little jarring for users when it happens.

**Comment by martinwoodward** [comment]
Closing now that PR #75 is merged. We can raise new issues on the merged in package now.  Thanks all!

**Comment by DarwinJS** [comment]
Great to see this move through the process!

Could someone please remove me as maintainer as I won't want to be
receiving the messages for the package - especially if the packaging is
automated.

Thanks!
D.

**Comment by gep13** [comment]
@DarwinJS I have removed you as a maintainer of the package :+1:
