### ISSUE TITLE
Formatting isn't working

### ISSUE THREAD

**Issue by dhcowgirl** [OpenLiveWriter/OpenLiveWriter#665]
I haven't used Open Live Writer in a month.  Opened it today to write a blog post and cannot get any formatting to work properly.
Inserting a Table did not work correctly.
Trying to enlarge font size didn't work.
I gave up.
What's going on?  How can this be fixed? 
I need to begin writing my blog posts again.  
I love Live Writer, please help.
Thank you,
Diane

**Comment by Mattadlard** [comment]
Having same issues suddenly, table will not work, and creating issues when you try and delete old ones with sudden size change.

**Comment by dhcowgirl** [comment]
Are there actually real people still supporting this wonderful program?
I love Open Live Writer.  I use it for my blog every week.
I very much miss being able to add my jpg's and upload them to Blogger. That feature doesn’t work any more. 
I also miss how the tables used to work. 
But, even so, I still love this program. 
Are there any plans to update the program?

Thanks again,
Diane

**Comment by nvella** [comment]
Hi Dianne,

I'm a relatively new contributor on this project, and was the developer behind the fix for this specific issue and others. There has been a lull in the amount of contributions as of late, and I'm trying my best to try and kick-start interest in the project again, by fixing long-standing bugs as well as implementing new features that hopefully will pique the interest of new developers.

The fix for this specific issue was merged in through pull request #830, and should appear in the next official release. With the fix, tables are visible again and can be resized, and columns/rows/cells can be copied and pasted. Unfortunately, I don't have any information as to when that when the next release will be finalized, but rest assured that the project isn't dead, and that these bug-fixes and others will be making their way out to users in the near future.

Thanks for showing your support!
Nick

**Comment by dhcowgirl** [comment]
Oh boy!!!  👏🏻👏🏻😃😃👏🏻👏🏻❤️
