### ISSUE TITLE
Error Code 500

### ISSUE THREAD

**Issue by bkford1** [OpenLiveWriter/OpenLiveWriter#710]
Never had a problem before today. Have double-checked account information. Blog is set up successfully. But will not publish. Error Code 500. Help?

**Comment by Rob2540** [comment]
same here...

**Comment by dnershi** [comment]
Please note that Issues 709, 710, 711, 713 and 714 all relate to this same issue.

**Comment by nvella** [comment]
Hi,

As of PR #810 images now upload to Google Drive, as Google has completely removed the ability for third-party apps to upload images to Blogger, and images uploaded to Google Photos cannot be programmatically embedded. I'll close this issue for now, as the fix is currently in the developer builds and should be making it's way out to users in the next release. Please don't hesitate to get back in touch if you have any further questions. 👍 Cheers
