### ISSUE TITLE
Open Live Writer won't publish images to Blogger

### ISSUE THREAD

**Issue by legalese22** [OpenLiveWriter/OpenLiveWriter#711]
Hi, when I try publishing an image I get this error. I am using version 0.6.2.0 in Windows 10. 

Thanks

![image](https://user-images.githubusercontent.com/28502793/35316744-2ae16f74-00cb-11e8-84fb-85bff9fe4467.png)

**Comment by RaviRatlami** [comment]
I am also facing same issues since yesterday. Please have a look ASAP. Regards. 
PS - Big thanks for this great tool. using it since initial WLW days.

**Comment by toobob** [comment]
work-around is to insert images by posting "from the web" rather than "from my computer" - see https://github.com/OpenLiveWriter/OpenLiveWriter/issues/709

**Comment by SteveP-UK** [comment]
I tried 'inserting from web' but this isn't working for me either. I'm on Windows 10 latest release and OLW 0.6.2

![image](https://user-images.githubusercontent.com/16260144/35343358-5c81ef2a-0122-11e8-97ae-bff7a805e207.png)

**Comment by denhamdagger** [comment]
Same here.

**Comment by farsideoffifty** [comment]
Same issue a problem between OLW and Google Photos  I have tried everything.  Please help!

**Comment by MickeytheKid** [comment]
Same issues here with Windows 10 and Open Live Writer.

**Comment by dnershi** [comment]
Please note that Issues 709, 710, 711, 713 and 714 all relate to this same issue.

**Comment by asiliuk5** [comment]
Still a problem... It's taking some time to fix it...

**Comment by nvella** [comment]
Hi,

As of PR #810 images now upload to Google Drive, as Google has completely removed the ability for third-party apps to upload images to Blogger, and images uploaded to Google Photos cannot be programmatically embedded. I'll close this issue for now, as the fix is currently in the developer builds and should be making it's way out to users in the next release. Please don't hesitate to get back in touch if you have any further questions. 👍 Cheers
