### ISSUE TITLE
Can't publish

### ISSUE THREAD

**Issue by jal2684** [OpenLiveWriter/OpenLiveWriter#713]
Since yesterday I can´t publish in Blogger, using OpenLiveWriter.

If only text ok! If text and pictures it returns the following message:  The remote server returned an error: (500) Internal Server Error.

The pictures are in the blog service:  Google Photos

Can you solve my problem, please?

**Comment by comstech23** [comment]
The same thing has just happened to me. Please help!!! 

Thank you!!

**Comment by Veshengro** [comment]
Same here but will publish when there are no pictures included.

**Comment by Romanyrambler** [comment]
The same problem is happening to us also here in New Zealand

Robin

**Comment by dnershi** [comment]
I also have the same issue. I am Windows 10 and Blogger. I get the Error 500 message. It will publish if there are no photos. I created a second Open Live Writer Google Photos album, but that didn't work.

**Comment by junction13** [comment]
Same for me too - just after a Window 10 update - please fix asap

**Comment by dnershi** [comment]
Please note that Issues 709, 710, 711, 713 and 714 all relate to this same issue.

**Comment by Romanyrambler** [comment]
We seem to be able to publish again now in NZ. No notification though, would have been nice.

**Comment by nvella** [comment]
Hi,

As of PR #810 images now upload to Google Drive, as Google has completely removed the ability for third-party apps to upload images to Blogger, and images uploaded to Google Photos cannot be programmatically embedded. I'll close this issue for now, as the fix is currently in the developer builds and should be making it's way out to users in the next release. Please don't hesitate to get back in touch if you have any further questions. 👍 Cheers
