### ISSUE TITLE
photos published by OLW started not showing

### ISSUE THREAD

**Issue by shengyenho** [OpenLiveWriter/OpenLiveWriter#714]
In addition to the 500 internal error issue that has been filed on other ticket, today I started experiencing another issue with all articles published by OLW.

All articles included photos upload from my computer and published by OLW stop showing photos. They were fine until today.
Those photo are linked to https://lh3.googleusercontent.com/
All articles I published with blogger after I got 500 error are showing photos fine.

I guess google photo is changing its API and cause all of recent issue with OLW.
Sadly, I have to switch back to blogger to publish articles. :(

**Comment by dnershi** [comment]
Please note that Issues 709, 710, 711, 713 and 714 all relate to this same issue.

**Comment by shengyenho** [comment]
it might be the same google API issue, but this is new phenomenon that all image link from googleusercontent.com is failing.
I just spent whole night to re-link the images with blogger editor, every single article.
So it is not just OLD being not able to publish new article with local image but old articles got affected.

**Comment by nvella** [comment]
Hi,

As of PR #810 images now upload to Google Drive, as Google has completely removed the ability for third-party apps to upload images to Blogger, and images uploaded to Google Photos cannot be programmatically embedded. I'll close this issue for now, as the fix is currently in the developer builds and should be making it's way out to users in the next release. Please don't hesitate to get back in touch if you have any further questions. 👍 Cheers
