### ISSUE TITLE
Add A Blogger Blog to OLW

### ISSUE THREAD

**Issue by toobob** [OpenLiveWriter/OpenLiveWriter#731]
for months now, attempts to add a blogger blog to OLW throws a "Backend 500 Error  (see #724 & #719) - is there any way to transfer OLW "settings" from an installation on my old windows 10 pc already setup with my blogs before this bug appeared to my new windows 10 pc.
? i am completely unable to add my blogs to my OLW installation on my new pc.

**Comment by nvella** [comment]
Hi @toobob, and apologies for the delay,

Open Live Writer stores it's configuration, including blogs added, under registry key `HKEY_CURRENT_USER\Software\OpenLiveWriter`, as well as some auxiliary settings and authentication tokens in `%appdata%\OpenLiveWriter`. Copying that registry key and folder should be all that's needed to transfer the application configuration to another computer.

However before doing that, I recommend retrying adding your Blogger blog again. Various patches have been made to the Blogger client in the year since this issue was lodged, as well as a patch for image uploading which is currently being tested in the development builds. I'll close this issue for now, but if this issue still persists for you feel free to get back in touch 👍 Cheers
