### ISSUE TITLE
Sharing violation when posting (Blogger)

### ISSUE THREAD

**Issue by NenoLoje** [OpenLiveWriter/OpenLiveWriter#763]
When trying to publish a new blog post, an unexpected error is shown:

![error-report](https://user-images.githubusercontent.com/13981145/45421158-84884580-b68c-11e8-8682-6d2b59b600d2.png)

Attached: [error-report-when-posting.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/2374819/error-report-when-posting.txt)

**Comment by jasonbrown1965** [comment]
Hmmm ... the seeming slow demise of OLW leaves us Windows hos pretty much without a free, let alone an open source one? 

What would a full-price rescue mission cost? $5,000 in app expert fees? $50,000? Could we do a crowdfunder, e.g. SOS - save our software? And where's the best place for OLW users to discuss non-tech ideas further?

**Comment by nvella** [comment]
Hi @NenoLoje. I know it's been a while since you reported this issue, but do you remember much more about when this error occurred? Was it consistent, or did it only appear sometimes? The error logs indicate that it's related to a 'sharing violation' on saving the submitted post locally. One possibility is that another OLW instance was holding a lock on that specific file, but that shouldn't be the case on new blog posts.

**Comment by NenoLoje** [comment]
Hi @nvella. Good question - no I don't remember the details. I'm happy to close this for now, and reopen it again if I hit this again. I haven't used OLW much - as it has not been working reliably for Blgoger and on high DPI screens. Now, it seems that commited you fixes to both those issues (awesome!), so I'm keen to try the new version - and will report back, how it goes. :)

**Comment by nvella** [comment]
Easy done 👍 Please don't hesitate to get back in touch if you do bump into this error again. Cheers
