### ISSUE TITLE
Error when posting the error report

### ISSUE THREAD

**Issue by NenoLoje** [OpenLiveWriter/OpenLiveWriter#764]
After the **Unexpected Error** dialog is shown, trying to send the error report fails with another unexpected error. :)

> Unexpected Error Occurred
> An unexpected error has occurred within the application.
> System.NullReferenceException:
>
> Object reference not set to an instance of an object.
>    at OpenLiveWriter.CoreServices.Diagnostics.HockeyAppProxy.SendDataAsync(String crashData, String description)
>    at OpenLiveWriter.CoreServices.Diagnostics.HockeyAppProxy.<UploadExceptionAsync>d__27.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object 
> state)

Attached: [error-report-when-sending-an-error.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/2374831/error-report-when-sending-an-error.txt)

Screenshot:
![error-report](https://user-images.githubusercontent.com/13981145/45421357-08dac880-b68d-11e8-8337-0cbca9ad58be.png)

**Comment by nvella** [comment]
I attempted to reproduce this by throwing my own test exception, and it seemed to work successfully. I'd assume this specific instance was caused by a network failure, as it occurred in the SendDataAsync method for the HockeyApp error reporting. More testing would need to be undertaken to determine the root cause of this, and if it is a networking error, we would have to decide what to do with the error we were unable to report. Maybe store it for later submission?

**Comment by NenoLoje** [comment]
Thanks for taking time to look into this, @nvella. Glad if it works now.

Storing it for later submission would certainly be interesting (and allow to catch bugs which only happen when writing offline), but it's not a 'must' and since it's not part of this issue, I'm marking it as resolved.
