### ISSUE TITLE
Suggestion: Static Site Generator

### ISSUE THREAD

**Issue by csrpazzi** [OpenLiveWriter/OpenLiveWriter#778]
It would be awesome to integrate to a static site generator like Jekyll or Hugo or even Gatsby

**Comment by nvella** [comment]
Hi all, 

I intend to begin development on this feature in my `static-site-generator` branch. I envision a highly configurable integration, which would work with a wide array of static site generators. The feature will be initially tailored to advanced users, as it will assume that the user already has the folder structure for a static site setup on their machine. I'll provide some basic documentation below on what I intend to implement.

### Setup use-case
1. The user has a static site on their local disk, from a `git clone` or otherwise.
2. User adds a new blog to their OLW and selects 'Static Site Generator' as the blog type.
3. OLW presents the following settings for configuration:
    - (drop-down) Preset. This will allow the user to easily select from a variety of preset SSG configurations.
    - (string) Site directory. This can be selected from a folder picker.
    - (string) Posts directory name.
    - (string) Pages directory name.
    - (string) Build command. This can be left blank for a Github Pages publish.
    - (string) Publish command.
4. User configures their site and confirms.
5. Blog set-up continues as usual.

### New post use-case
1. The user composes a post as usual. Categories, tags and post date would be made available.
2. User clicks Publish.
3. OLW renders the post to a HTML file, placing it in `$SITE_DIRECTORY/$POSTS_DIRECTORY/$DATE-$TITLE.html`. The option to customize the output filename format may be added later.
   3a. Appropriate YAML front-matter is added to the render. The title, date, categories and tags would be added, the option for further customization may be added later.
4. OLW runs the build command, if there is one.
5. OLW runs the publish command.

Page posting would behave in a similar manner, probably without post dates.

### Load post use-case
1. The user navigates to the 'Open recent post' dialog.
2. OLW loads posts from the Posts directory and parses their YAML front-matters.
3. User selects Post to load.
4. OLW loads and parses post, then displays it as usual.

The basic feature would form the basis for further expansion. For example, this component could be built upon to provide 'zero-config' Github Pages support. Markdown could also be possible in the future as a general editor implementation, rather than being specific to the blog client.

**Comment by nvella** [comment]
# To-do list

- [ ] Implementation of StaticSiteGeneratorClient BlogClient
    - [ ] ProtocolName
    - [ ] Options
    - [ ] OverrideOptions
    - [ ] VerifyCredentials
    - [ ] GetUsersBlogs
    - [ ] GetCategories
    - [ ] GetKeywords
    - [ ] GetRecentPosts
    - [ ] NewPost
    - [ ] EditPost
    - [ ] GetPost
    - [ ] DeletePost
    - [ ] GetPage
    - [ ] GetPageList
    - [ ] GetPages
    - [ ] NewPage
    - [ ] EditPage
    - [ ] DeletePage
    - [ ] GetAuthors
    - [ ] DoesFileNeedUpload
    - [ ] DoBeforePublishUploadWork
    - [ ] DoAfterPublishUploadWork
    - [ ] AddCategory
    - [ ] SuggestCategories
    - [ ] SendAuthenticatedHttpRequest
    - [ ] GetImageEndpoints
- [ ] Creation wizard
- [ ] Settings panel

**Comment by nvella** [comment]
Some work in progress wizard screenshots:
![image](https://user-images.githubusercontent.com/8158648/60396522-06971b80-9b86-11e9-807a-aab9283d7c65.png)
![image](https://user-images.githubusercontent.com/8158648/60396525-0ac33900-9b86-11e9-9ae9-9fd8aa4ec1aa.png)

**Comment by nvella** [comment]
Development is currently progressing at a steady pace. I now have the wizard adding and saving the site successfully, and OLW can switch to the blog. When the Publish button is clicked, the NewPost method in the StaticSiteClient is called. I am now working towards implementing these StaticSiteClient methods.

**Comment by nvella** [comment]
Currently working on expanding the wizard to multiple pages, as well as Jekyll config auto-detection. NewPost method is mostly complete, posts successfully but is yet to open a browser on the new post.

**Comment by nvella** [comment]
Thought I'd quickly check in again. Most of my work over the last few days has been on expanding the wizard to multiple pages, as to capture more configuration from the user. I've made many options available, hopefully allowing for support of the highest amount of static site generators possible. There will also be an auto-detection feature present as well, where OLW will try to pre-fill these values based on files already existing in the static site project folder.

![image](https://user-images.githubusercontent.com/8158648/60770726-abcf6800-a121-11e9-9f95-5d954a6b7b26.png)
![image](https://user-images.githubusercontent.com/8158648/60770735-b853c080-a121-11e9-8d45-0c735f594316.png)
![image](https://user-images.githubusercontent.com/8158648/60770740-c0abfb80-a121-11e9-8c61-971a13335d44.png)
![image](https://user-images.githubusercontent.com/8158648/60770743-c9043680-a121-11e9-9e69-26a2cf0ed6ec.png)
![image](https://user-images.githubusercontent.com/8158648/60770770-ffda4c80-a121-11e9-99e5-f21321ca0146.png)
![image](https://user-images.githubusercontent.com/8158648/60770782-1aacc100-a122-11e9-9f73-7670b3210e79.png)

**Comment by nvella** [comment]
Finally have the wizard the way I like it for now, so moving on to the config auto-detection. I'll be targeting Jekyll for now as it's also what;s targeted by GitHub Pages, but eventually I'd like to bring in support for as many generators as possible.

Nearly every generator has different config vars, front-matter keys, formatting, etc which would require altering of the wizard to accommodate this. I can see it getting to the point where I'll be required to introduce an 'advanced configuration' form which will present every config option in a table, leaving only the most critical settings to the wizard.

**Comment by nvella** [comment]
Have decided on the set of classes that I'll need for further implementation of StaticSiteClient as specified by IBlogClient. I've designed a (admittedly shocking) UML class diagram and written up a small hacking manual in the `docs` directory for anyone else wishing to work on the integration, you can find the [initial version of the document here](https://github.com/nvella/OpenLiveWriter/blob/static-site-generator/docs/Hacking%20-%20Static%20Site%20Client.md).

I've implemented a few methods in these classes, such as custom front-matter generation, on-disk published post management as well as other features. These classes will slowly see more methods added to them to accommodate the full range of blog client features.

**Comment by nvella** [comment]
CRUD operations on Posts now mostly complete for an initial revision. Next steps are pages, images, theme detection, an 'advanced settings' dialog and a general tidy up of the code so far. At that point it should be ready for a PR 😄

**Comment by nvella** [comment]
Changes merged in #844. 🎉
