### ISSUE TITLE
Cannot configure a DreamWidth (LiveJournal API-based) blog

### ISSUE THREAD

**Issue by starseer** [OpenLiveWriter/OpenLiveWriter#80]
As someone who uses DreamWidth for my primary journal, I would enjoy seeing native support for blogs with LiveJournal-based APIs . Currently, DreamWidth's own wiki suggests using the APIs mentioned here: http://www.livejournal.com/doc/server/ljp.csp.protocol.html

At the least, I would like to see support for security levels (_Public_/_Friends Only_/_Private_), age restrictions, and LiveJournal-style tags, but simple ease of setup would be wonderful in itself.

**Comment by timheuer** [comment]
LiveJournal is supported.  Are you having problems connecting your account?

**Comment by starseer** [comment]
Yes, actually. This is the error I get when attempting to add my DreamWidth journal:

![error](http://prismdragon.net/images/2015-12-10.png)

This occurs whether the user/pass is correct or incorrect.

**Comment by timheuer** [comment]
Found the issue @starseer.  Looks like DreamWidth isn't a 'full' provider that we expect in the metadata.  I'm taking a look to see how we can make this work easily to get past the first step here.

**Comment by timheuer** [comment]
Submitted a fix for this.  Found another error in trying to upload pictures so it may be that some things aren't supported by DreamWidth still.

**Comment by starseer** [comment]
Thank you very much for the work. It might be wise for someone with more technical knowledge to submit an issue report to DreamWidth's own tracker in regards to picture uploads, to see if they have an answer.

**Comment by timheuer** [comment]
@starseer Yeah this is more about a few things:
* DreamWidth could better annotate the sites to exactly which APIs are supported (OLW has 'blog API detection' and DreamWidth is just resulting in a generic "AtomPub" provider.
* Problem with OLW is that the AtomPub generic API provider is not complete (doesn't support pushing images/file uploads, etc)

This could be solved with:
* Finishing the AtomPub generic code in OLW (which is Issue #88)
* Getting DreamWidth to add HTML <meta> tags for all the types of API they support (looks like they support Blogger and LiveJournal in **some** way, but they would need to add the <meta> tags in order to make this smarter for OLW

For now I would pay attention to Issue #88 as the likely resolution.  I will play around with DreamWidth settings to see if I can provide a workaround for you to fix *your* site.
