### ISSUE TITLE
No photos on celll phone from blogger Please Help!!

### ISSUE THREAD

**Issue by JoniWebb** [OpenLiveWriter/OpenLiveWriter#870]
I really need someone to help me.   Two years worth of blogs on Open Live Writer are not showing photos on cell devices!  It happened overnight.

Now I can't even BLOG on Live Writer without the photos disappearing after I save the blog and reopen it.  

Please someone, I am desperate. 

Thanks.

**Comment by nvella** [comment]
Hi @JoniWebb, It seems you have raised two issues here.

Regarding the first first issue with photos not showing, it seems this is an issue related to how Live Writer was uploading photos before the switch to Google Drive. I have picked a post that was published when Live Writer was still using Google Picasa for photo upload (https://cotedetexas.blogspot.com/2017/12/what-dianas-apartment-looks-like-today.html). The photos on this post are not displaying for me, even on my computer. When right clicking on one of the photo placeholders and viewing it in a new tab, a Google log-in page is displayed, which leads me to believe that the permissions on these previously uploaded photos have somehow changed. Have you recently changed the privacy settings on these photos?

Regarding the second issue, I'd ask which version of Open Live Writer you are using, and where you downloaded it from. Due to Google discontinuing Picasa, we've had to change over to using Google Drive for photo upload. This fix will be included in release 0.7, which we are currently working on releasing to the public as soon as possible. Older releases currently fail to post to Blogger if the post contains photos.

Cheers, Nick

**Comment by JoniWebb** [comment]
Nick, thank you for answering.  The blog you picked does show photos for me on my computer.  I nailed it down to 2017-2019 for the phone.
Do you have any clue why overnight last week it would change for me?   I have so many readers emailing me about this.  What can I do?
I just reloaded the live writer when it started TWICE now.  Should I do it again?  AS I SAID, I can't even BLOG now using livewriter because i love the photo.  i blog using   photos/blogger.     Any clue what I can do to restore the cell phone blogs for those 2 years?  And I want to use Livewriter!!!!  What should I do?
J




----- Original Message -----

**Comment by JoniWebb** [comment]
Nick, I am BEGGING you to help me.   This all started last week.  I've been on live writer for 12 years.  Two entire years of my blog are useless now.   This is how I make my living.   I have NO clue what happened.  The ONLY thing i can think of is I put a Reward Style widget on the blog.  I deleted that post when I thought it might be that widget causing it.   Is there anyone that can look at my html and see if that widget is causing this?   I can pay you.    Seriously, I am desperate to fix this.  I have even gone back to old blogs and tried to edit them and publish to see if the photos show up but they dont.   Clueless.   Could it be a widget?

**Comment by JoniWebb** [comment]
One other question about the google drive?  would this have effected me just this past week?  I"m on Blogger.  I switched from Picasa a few years ago.  What would have caused this to happen all of a sudden, when I changed nothing.

**Comment by JoniWebb** [comment]
NEVER MIND.   i FIXED IT!!!   I added the Share option to the old folders.

Thanks for all your help!!!!!!!!!!!!!!!!!!

So happy!!!!

**Comment by nvella** [comment]
Glad to hear you fixed it!
