### ISSUE TITLE
Cannot sign in to blogger, getting "app is blocked" message

### ISSUE THREAD

**Issue by rsadykoff** [OpenLiveWriter/OpenLiveWriter#935]
Hello,

I am getting the error message trying to configure OpenWriter to connect to Google blogger:

This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

Tried with the version downloaded from the website as well as app from MS Store - no luck :( Could you have a look at it, please?

Best regards,
Rustam.
![Screenshot 2021-05-11 103402](https://user-images.githubusercontent.com/24512860/117793756-6fe91a80-b244-11eb-915f-41ff0fc28df1.png)

**Comment by JoniWebb** [comment]
that was wrong.   try this instead.


https://www.mybloggertricks.com/2015/12/fixing-open-live-writer-errors.html

**Comment by rsadykoff** [comment]
> that was wrong. try this instead.
> 
> https://www.mybloggertricks.com/2015/12/fixing-open-live-writer-errors.html

Hello, Joni!

That's great! The version in that link did help with my problem! I even tried new version, but it had a different error.

Many thanks for your help,
Rustam.

**Comment by shanselman** [comment]
Thanks for reporting this and for helping Open Live Writer over the years. We are doing an issue-bankruptcy cleanup so we can make the repository maintainable again and focus on current, actionable work. This older issue is being closed as part of that cleanup, not because it was unimportant. If this still reproduces in the current code or is still relevant to the revitalization work, please open a fresh issue with current details and we will triage it going forward.
